// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AutoSubmitController from "controllers/auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import BulkDeleteController from "controllers/bulk_delete_controller"
application.register("bulk-delete", BulkDeleteController)

import BulkEditController from "controllers/bulk_edit_controller"
application.register("bulk-edit", BulkEditController)

import CareDetailsController from "controllers/care_details_controller"
application.register("care-details", CareDetailsController)

import CopyController from "controllers/copy_controller"
application.register("copy", CopyController)

import DismissController from "controllers/dismiss_controller"
application.register("dismiss", DismissController)

import DynamicEmailsController from "controllers/dynamic_emails_controller"
application.register("dynamic-emails", DynamicEmailsController)

import EmailSuggestionController from "controllers/email_suggestion_controller"
application.register("email-suggestion", EmailSuggestionController)

import ExpireController from "controllers/expire_controller"
application.register("expire", ExpireController)

import FilterFormController from "controllers/filter_form_controller"
application.register("filter-form", FilterFormController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import KeepOnRefreshController from "controllers/keep_on_refresh_controller"
application.register("keep-on-refresh", KeepOnRefreshController)

import LeftAmountController from "controllers/left_amount_controller"
application.register("left-amount", LeftAmountController)

import OcrUploadController from "controllers/ocr_upload_controller"
application.register("ocr-upload", OcrUploadController)

import PasswordFieldController from "controllers/password_field_controller"
application.register("password-field", PasswordFieldController)

import PushController from "controllers/push_controller"
application.register("push", PushController)

import RangeFormController from "controllers/range_form_controller"
application.register("range-form", RangeFormController)

import RoutineFieldsController from "controllers/routine_fields_controller"
application.register("routine-fields", RoutineFieldsController)

import ShareAndDownloadController from "controllers/share_and_download_controller"
application.register("share-and-download", ShareAndDownloadController)

import ShareBridgeController from "controllers/share_bridge_controller"
application.register("share-bridge", ShareBridgeController)

import TimeZoneController from "controllers/time_zone_controller"
application.register("time-zone", TimeZoneController)

import ToastController from "controllers/toast_controller"
application.register("toast", ToastController)

import TrackerFormController from "controllers/tracker_form_controller"
application.register("tracker-form", TrackerFormController)
