// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BulkDeleteController from "controllers/bulk_delete_controller"
application.register("bulk-delete", BulkDeleteController)

import FilterFormController from "controllers/filter_form_controller"
application.register("filter-form", FilterFormController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import LeftAmountController from "controllers/left_amount_controller"
application.register("left-amount", LeftAmountController)

import OcrUploadController from "controllers/ocr_upload_controller"
application.register("ocr-upload", OcrUploadController)

import RangeFormController from "controllers/range_form_controller"
application.register("range-form", RangeFormController)

import ShareAndDownloadController from "controllers/share_and_download_controller"
application.register("share-and-download", ShareAndDownloadController)

import ShareBridgeController from "controllers/share_bridge_controller"
application.register("share-bridge", ShareBridgeController)

import TimeZoneController from "controllers/time_zone_controller"
application.register("time-zone", TimeZoneController)

import ToastController from "controllers/toast_controller"
application.register("toast", ToastController)

import TrackerFormController from "controllers/tracker_form_controller"
application.register("tracker-form", TrackerFormController)
