# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  pet_weight_reminder:
    command: "Rails.application.load_tasks; Rake::Task['notifications:weigh_pets'].invoke"
    schedule: every day at 9am
  user_backups:
    class: UserBackupJob
    schedule: every 5 days at 3am
  db_backup:
    command: "bin/rails db:backup"
    schedule: every day at 4am
